FROM apache/airflow:latest

USER root
RUN apt-get update && \
    apt-get -y install git && \
    apt-get clean

USER airflow

RUN pip install dbt-core dbt-snowflake
RUN git clone https://github.com/Uddhav18/crypto_dbt.git